[package]
name = "rustpar"
version = "0.1.0"
edition = "2021"

[dependencies]
time = "0.3.36"
reqwest = "0.12.7"
scraper = "0.20.0"
tokio = { version = "1.40.0", features = ["rt", "rt-multi-thread", "macros"] }
